

import com.mycompany.views.*;
import com.mycompany.ilib.DAOBooksImpl;
import com.mycompany.ilib.DAOLendingsImpl;
import com.mycompany.ilib.DAOUsersImpl;
import com.mycompany.interfaces.DAOBooks;
import com.mycompany.interfaces.DAOLendings;
import com.mycompany.interfaces.DAOUsers;
import com.mycompany.models.Lendings;
import com.mycompany.utils.Utils;
import java.awt.Color;
import java.util.Date;
import com.mycompany.models.Users;
import com.mycompany.models.Books;
import com.mycompany.models.Lendings;
import java.util.List;
import javax.swing.JOptionPane;

public class Devoluciones extends javax.swing.JPanel {

    private final int MAX_DAYS_RETURN = 5;
    private final int COST_DAY_SANC = 10;
    
      public Devoluciones() {
    initComponents();
    cargarUsuarios();
    cargarLibros();
}
    
       /**
     * Este método realiza una búsqueda de usuarios por nombre (o parte del nombre)
     * y actualiza el ComboUsuarios con los resultados.
     * Suponiendo que en DAOUsers hay un método getUsersByName(String) que retorna una lista.
     */


private void cargarUsuarios() {
    try {
        DAOUsers daoUsers = new DAOUsersImpl();
        List<Users> listaUsuarios = daoUsers.listar("");

        ComboUsuarios.removeAllItems();
        for (Users u : listaUsuarios) {
            ComboUsuarios.addItem(u.getName());
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + e.getMessage());
    }
}

private void cargarLibros() {
    try {
        DAOBooks daoBooks = new DAOBooksImpl();
        List<Books> listaLibros = daoBooks.listar("");
        ComboLibros.removeAllItems();
        for (Books b : listaLibros) {
            ComboLibros.addItem(b.getTitle());
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar libros: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        title = new javax.swing.JLabel();
        folioLbl = new javax.swing.JLabel();
        libroIdLbl = new javax.swing.JLabel();
        button = new javax.swing.JButton();
        botonBuscarLibros = new javax.swing.JButton();
        ComboUsuarios = new javax.swing.JComboBox<>();
        bucarUsuarios = new javax.swing.JTextField();
        BuscarLibros = new javax.swing.JTextField();
        ComboLibros = new javax.swing.JComboBox<>();
        botonBuscarUsuarios = new javax.swing.JButton();
        usuarioslbl = new javax.swing.JLabel();
        libroslbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 430));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        title.setText("Devolución de Libro");

        folioLbl.setText("Nombre Usuario");

        libroIdLbl.setText("Nombre Libro");

        button.setBackground(new java.awt.Color(18, 90, 173));
        button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setText("Devolver");
        button.setBorderPainted(false);
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        botonBuscarLibros.setBackground(new java.awt.Color(18, 90, 173));
        botonBuscarLibros.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonBuscarLibros.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscarLibros.setText("Buscar");
        botonBuscarLibros.setBorderPainted(false);
        botonBuscarLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonBuscarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarLibrosActionPerformed(evt);
            }
        });

        ComboUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboUsuariosActionPerformed(evt);
            }
        });

        ComboLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboLibrosActionPerformed(evt);
            }
        });

        botonBuscarUsuarios.setBackground(new java.awt.Color(18, 90, 173));
        botonBuscarUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonBuscarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscarUsuarios.setText("Buscar");
        botonBuscarUsuarios.setBorderPainted(false);
        botonBuscarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonBuscarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarUsuariosActionPerformed(evt);
            }
        });

        usuarioslbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        libroslbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(folioLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(199, 199, 199))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(167, 167, 167))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(libroIdLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(223, 223, 223))
                    .addComponent(button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usuarioslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(libroslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BuscarLibros, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboUsuarios, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bucarUsuarios, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonBuscarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonBuscarLibros))
                .addGap(13, 13, 13))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(63, 63, 63)
                        .addComponent(folioLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(usuarioslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(libroIdLbl)
                        .addGap(18, 18, 18)
                        .addComponent(libroslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bucarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ComboUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(ComboLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
   String selectedUser = (String) ComboUsuarios.getSelectedItem();
    String selectedBook = (String) ComboLibros.getSelectedItem();

    if (selectedUser != null && selectedBook != null) {
        try {
            DAOUsers daoUsers = new DAOUsersImpl();
            DAOBooks daoBooks = new DAOBooksImpl();
            DAOLendings daoLendings = new DAOLendingsImpl();

            // Obtener los IDs del usuario y del libro
            int userId = daoUsers.getUserIdByName(selectedUser);
            int bookId = daoBooks.getBookIdByTitle(selectedBook);

            // Obtener el préstamo activo del usuario y libro seleccionados
            Lendings lending = daoLendings.getLending(new Users(userId), new Books(bookId));

            if (lending == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No existe un préstamo activo para este usuario y libro.");
                return;
            }

            // Registrar la devolución
            lending.setDate_return(java.time.LocalDate.now().toString());
            daoLendings.modificar(lending);

            // Confirmación
            javax.swing.JOptionPane.showMessageDialog(this, "Libro devuelto con éxito.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al registrar la devolución: " + e.getMessage());
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor seleccione un usuario y un libro.");
    }


    }//GEN-LAST:event_buttonActionPerformed

    private void botonBuscarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarLibrosActionPerformed
       
    String search = bucarUsuarios.getText().trim();
    if (search.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un nombre de usuario para buscar.");
        return;
    }
    try {
        DAOUsers daoUsers = new DAOUsersImpl();
        List<Users> listaUsuarios = daoUsers.listar(search);
        ComboUsuarios.removeAllItems();
        if (listaUsuarios.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontraron usuarios con ese nombre.");
        } else {
            for (Users u : listaUsuarios) {
                ComboUsuarios.addItem(u.getName());
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al buscar usuarios: " + e.getMessage());
    }



   

    }//GEN-LAST:event_botonBuscarLibrosActionPerformed

    private void ComboUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboUsuariosActionPerformed
        
    }//GEN-LAST:event_ComboUsuariosActionPerformed

    private void ComboLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboLibrosActionPerformed
        
    }//GEN-LAST:event_ComboLibrosActionPerformed

    private void botonBuscarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarUsuariosActionPerformed
                 String search = BuscarLibros.getText().trim();
    if (search.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un título de libro para buscar.");
        return;
    }
    try {
        DAOBooks daoBooks = new DAOBooksImpl();
        List<Books> listaLibros = daoBooks.listar(search);
        ComboLibros.removeAllItems();
        if (listaLibros.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontraron libros con ese título.");
        } else {
            for (Books b : listaLibros) {
                ComboLibros.addItem(b.getTitle());
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al buscar libros: " + e.getMessage());
    }

    }//GEN-LAST:event_botonBuscarUsuariosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BuscarLibros;
    private javax.swing.JComboBox<String> ComboLibros;
    private javax.swing.JComboBox<String> ComboUsuarios;
    private javax.swing.JPanel bg;
    private javax.swing.JButton botonBuscarLibros;
    private javax.swing.JButton botonBuscarUsuarios;
    private javax.swing.JTextField bucarUsuarios;
    private javax.swing.JButton button;
    private javax.swing.JLabel folioLbl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel libroIdLbl;
    private javax.swing.JLabel libroslbl;
    private javax.swing.JLabel title;
    private javax.swing.JLabel usuarioslbl;
    // End of variables declaration//GEN-END:variables
}
