

import com.mycompany.views.*;
import com.mycompany.ilib.DAOBooksImpl;
import com.mycompany.ilib.DAOLendingsImpl;
import com.mycompany.ilib.DAOUsersImpl;
import com.mycompany.interfaces.DAOBooks;
import com.mycompany.interfaces.DAOLendings;
import com.mycompany.interfaces.DAOUsers;
import com.mycompany.utils.Utils;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

public class Prestamos extends javax.swing.JPanel {

    public Prestamos() {
        initComponents();
        cargarUsuarios();
        cargarLibros();
        
    }
private void cargarUsuarios() {
    ComboUsuarios.removeAllItems();
    try {
        DAOUsers daoUsers = new DAOUsersImpl();
        daoUsers.listar("").forEach(user -> ComboUsuarios.addItem(user.getName()));
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + e.getMessage());
    }
}
private void cargarLibros() {
    ComboLibros.removeAllItems();
    try {
        DAOBooks daoBooks = new DAOBooksImpl();
        daoBooks.listar("").forEach(book -> ComboLibros.addItem(book.getTitle()));
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar libros: " + e.getMessage());
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        folioLbl = new javax.swing.JLabel();
        libroIdLbl = new javax.swing.JLabel();
        button = new javax.swing.JButton();
        ComboUsuarios = new javax.swing.JComboBox<>();
        bucarUsuarios = new javax.swing.JTextField();
        BuscarLibros = new javax.swing.JTextField();
        ComboLibros = new javax.swing.JComboBox<>();
        usuarioslbl = new javax.swing.JLabel();
        libroslbl = new javax.swing.JLabel();
        botonBuscarUsuarios = new javax.swing.JButton();
        botonBuscarLibros = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        folioLbl.setText("Nombre Usuario");

        libroIdLbl.setText("Nombre Libro");

        button.setBackground(new java.awt.Color(18, 90, 173));
        button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setText("Prestar");
        button.setBorderPainted(false);
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        ComboUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboUsuariosActionPerformed(evt);
            }
        });

        ComboLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboLibrosActionPerformed(evt);
            }
        });

        usuarioslbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        libroslbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonBuscarUsuarios.setBackground(new java.awt.Color(18, 90, 173));
        botonBuscarUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonBuscarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscarUsuarios.setText("Buscar");
        botonBuscarUsuarios.setBorderPainted(false);
        botonBuscarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonBuscarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarUsuariosActionPerformed(evt);
            }
        });

        botonBuscarLibros.setBackground(new java.awt.Color(18, 90, 173));
        botonBuscarLibros.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonBuscarLibros.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscarLibros.setText("Buscar");
        botonBuscarLibros.setBorderPainted(false);
        botonBuscarLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonBuscarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarLibrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BuscarLibros, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboUsuarios, javax.swing.GroupLayout.Alignment.LEADING, 0, 313, Short.MAX_VALUE)
                    .addComponent(bucarUsuarios, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboLibros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonBuscarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonBuscarLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                        .addComponent(folioLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(199, 199, 199))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                        .addComponent(libroIdLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(223, 223, 223))
                    .addComponent(button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(libroslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usuarioslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(folioLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(usuarioslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(libroIdLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(libroslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bucarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBuscarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ComboUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BuscarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBuscarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(ComboLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(60, 60, 60))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
   
    }//GEN-LAST:event_buttonActionPerformed

    private void ComboUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboUsuariosActionPerformed
        // TODO add your handling code here:
        
    String selectedUser = (String) ComboUsuarios.getSelectedItem();
    if (selectedUser != null) {
        usuarioslbl.setText(selectedUser);
    }


    }//GEN-LAST:event_ComboUsuariosActionPerformed

    private void botonBuscarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarUsuariosActionPerformed
String searchQuery = bucarUsuarios.getText().trim();
    ComboUsuarios.removeAllItems();
    try {
        DAOUsers daoUsers = new DAOUsersImpl();
        daoUsers.listar(searchQuery).forEach(user -> ComboUsuarios.addItem(user.getName()));
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al buscar usuarios: " + e.getMessage());
    }

    }//GEN-LAST:event_botonBuscarUsuariosActionPerformed

    private void botonBuscarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarLibrosActionPerformed
        // TODO add your handling code here:
        String searchQuery = BuscarLibros.getText().trim();
    ComboLibros.removeAllItems();
    try {
        DAOBooks daoBooks = new DAOBooksImpl();
        daoBooks.listar(searchQuery).forEach(book -> ComboLibros.addItem(book.getTitle()));
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al buscar libros: " + e.getMessage());
    }
    }//GEN-LAST:event_botonBuscarLibrosActionPerformed

    private void ComboLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboLibrosActionPerformed
        // TODO add your handling code here:
        String selectedBook = (String) ComboLibros.getSelectedItem();
    if (selectedBook != null) {
        libroslbl.setText(selectedBook);
    }
    }//GEN-LAST:event_ComboLibrosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BuscarLibros;
    private javax.swing.JComboBox<String> ComboLibros;
    private javax.swing.JComboBox<String> ComboUsuarios;
    private javax.swing.JPanel bg;
    private javax.swing.JButton botonBuscarLibros;
    private javax.swing.JButton botonBuscarUsuarios;
    private javax.swing.JTextField bucarUsuarios;
    private javax.swing.JButton button;
    private javax.swing.JLabel folioLbl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel libroIdLbl;
    private javax.swing.JLabel libroslbl;
    private javax.swing.JLabel usuarioslbl;
    // End of variables declaration//GEN-END:variables
}
